# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"
gem 'sinatra'
gem 'sinatra-activerecord'
gem 'sqlite3'
gem 'rake'
gem 'dotenv'
gem 'puma'
gem 'byebug'

group :test do
  gem "rspec"
  gem "rack-test"
end
